### ISSUE TITLE
Talk schedule page is a little confusing

### ISSUE THREAD

**Issue by fcurella** [djangocon/2015.djangocon.us#111]
* stack the days: day 1 on top, day 2 in the middle, day 3 on the bottom
* each talk slot spanning the full width and split in half
* if bored, also add a paginated version so I won't have to scroll forever on my phone on day 3

**Comment by fcurella** [comment]
Proposed mock-up

![screen shot 2015-07-29 at 3 49 32 pm](https://cloud.githubusercontent.com/assets/89607/8969483/78734e22-3609-11e5-809d-38ba4adf81f2.png)

**Comment by jefftriplett** [comment]
The old version we had to think about but it made sense. The new version is going to have lots of people in the wrong room because of the column association. We might be able to sort the group to make it work. Here's an example of the issue:

![](https://www.evernote.com/l/ABtzenOKRjtCRpkJ5Urcsh0aGVfklWuViPIB/image.png)
